stubs: smtpd: make it work with python 3.7
After upgrading to Debian 10 smtpd failed in two different ways, I assume it's
due to changes in python 3.7 compared to older 3.x releases.

error: uncaptured python exception, closing channel <smtpd.SMTPChannel connected 127.0.0.1:53896 at 0x7fa85ea22320> (<class 'TypeError'>:process_message() got an unexpected keyword argument 'mail_options' [/usr/lib/python3.7/asyncore.py|read|83] [/usr/lib/python3.7/asyncore.py|handle_read_event|422] [/usr/lib/python3.7/asynchat.py|handle_read|171] [/usr/lib/python3.7/smtpd.py|found_terminator|386])
^CTraceback (most recent call last):
  File "../smtpd", line 91, in <module>
    if __name__ == "__main__":
  File "../smtpd", line 87, in main

  File "../smtpd", line 70, in run

  File "/usr/lib/python3.7/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.7/asyncore.py", line 144, in poll
    r, w, e = select.select(r, w, e, timeout)

smtpd: test@example.com -> foo@example.com, bar@example.com
error: uncaptured python exception, closing channel <smtpd.SMTPChannel connected 127.0.0.1:53898 at 0x7f887b098358> (<class 'TypeError'>:write() argument must be str, not bytes [/usr/lib/python3.7/asyncore.py|read|83] [/usr/lib/python3.7/asyncore.py|handle_read_event|422] [/usr/lib/python3.7/asynchat.py|handle_read|171] [/usr/lib/python3.7/smtpd.py|found_terminator|386] [../smtpd|process_message|52])

Signed-off-by: Kalle Valo <kvalo@codeaurora.org>