pwcli: edit_file(): fix utf-8 handling
Editing and then sending an email with non-ascii characters failed with an
error below. This is because we were using strings and not bytes so switch
edit_file() to use bytes.

error: 'ascii' codec can't encode character '\xc8' in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "pwcli", line 3507, in run_shell
    args.func(args)
  File "pwcli", line 3224, in cmd_reply
    self.send_email(reply)
  File "pwcli", line 2232, in send_email
    server.send_message(msg)
  File "/usr/lib/python3.11/smtplib.py", line 984, in send_message
    g.flatten(msg_copy, linesep='\r\n')
  File "/usr/lib/python3.11/email/generator.py", line 116, in flatten
    self._write(msg)
  File "/usr/lib/python3.11/email/generator.py", line 181, in _write
    self._dispatch(msg)
  File "/usr/lib/python3.11/email/generator.py", line 218, in _dispatch
    meth(msg)
  File "/usr/lib/python3.11/email/generator.py", line 436, in _handle_text
    super(BytesGenerator,self)._handle_text(msg)
  File "/usr/lib/python3.11/email/generator.py", line 253, in _handle_text
    self._write_lines(payload)
  File "/usr/lib/python3.11/email/generator.py", line 155, in _write_lines
    self.write(line)
  File "/usr/lib/python3.11/email/generator.py", line 410, in write
    self._fp.write(s.encode('ascii', 'surrogateescape'))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode character '\xc8' in position 0: ordinal not in range(128)

Signed-off-by: Kalle Valo <quic_kvalo@quicinc.com>